# Generated by Django 3.0.2 on 2020-01-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('f_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=40)),
                ('phone', models.CharField(max_length=15)),
                ('description', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'contact',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('item_name', models.CharField(default='', max_length=5000)),
                ('name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(default='', max_length=40)),
                ('phone', models.CharField(default='', max_length=20)),
                ('address', models.CharField(default='', max_length=500)),
                ('country', models.CharField(default='', max_length=20)),
                ('city', models.CharField(default='', max_length=20)),
                ('zip_code', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('product_catagory', models.CharField(default='', max_length=100)),
                ('product_subcatagory', models.CharField(default='', max_length=100)),
                ('product_price', models.IntegerField(default=0)),
                ('product_desc', models.CharField(max_length=400)),
                ('product_time', models.DateField()),
                ('product_image', models.ImageField(default='', upload_to='shop/images')),
            ],
            options={
                'db_table': 'product',
            },
        ),
    ]
